### ISSUE TITLE
Missing docker-compose.yml files for elasticsearch etc

### ISSUE THREAD

**Issue by stedn** [dfci/matchminer-api#13]
I'm running into issues when trying to run matchminer UI locally.  I can't find in the documentation where the docker-compose yaml files are for the elasticsearch docker containers.  Can you advise where I should find that information.

Thanks

**Comment by ethansiegl** [comment]
Hmm, it looks like the compose file didn't make it into the repo. You could try something like this:

```
elastic:
    container_name: prod_elastic
    restart: always
    image: elasticsearch:2.4.0
    ports:
    - "9200:9200"
   network:
    - [your_network]
```

Also, there's a bash setup script here which might have what you're looking for
https://github.com/dfci/matchminer-https://github.com/dfci/matchminer-api/blob/master/setup.sh

**Comment by stedn** [comment]
Thanks, that setup script was where I realized that there should be a few compose files.

Lines 124-132 reference a few docker-compose commands that need config files.
```
cd ${WORK_DIR}/${DOCKER_IMG_PATH}
docker-compose up -d mongo
docker-compose run mongo-setup
docker rm ${MONGO_SETUP_CONTAINER}
docker-compose up -d api
docker-compose up -d elastic
docker-compose up -d connector
docker-compose up -d kibana
docker-compose up -d ui
```
Would it be possible to add the compose files?  Matchminer-ui isn't functional without them.  I will try the one you included above and let you know if that is enough to make it run.

**Comment by ethansiegl** [comment]
very sorry for the delayed response. I found this file in an old chat thread. Haven't had time to test it out but it might be what you're looking for 

```
version: "2.0"
services:
  mongo:
    restart: always
    image: mongo:latest
    command: --replSet "rs0"
    volumes:
      - ./data/mongo:/storage
      - ./data/db:/data/db
​
  mongo-setup:
    restart: "no"
    image: mongo:latest
    command: mongo mongo/matchminer --eval 'rs.initiate()'
    links:
      - mongo:mongo
​
  api:
    restart: "no"
    image: matchminer-demo-api:1.0.0
    command: dev
    ports:
      - 5555:5000
    volumes:
      - ./data/logs:/var/log/apache2
      - ./data/dev:/mm_staging
    environment:
      - MM_SETTINGS=PROD
      - MONGO_URI=mongodb://mongo:27017/matchminer?replicaSet=rs0
      - SSL_PORT=5555
      - API_ADDRESS=http://localhost:5000/api
      - API_TOKEN=fb4d6830-d3aa-481b-bcd6-270d69790e11
    links:
      - mongo
​
  elastic:
    restart: always
    image: elasticsearch:2.4.0
    ports:
      - 9200:9200
    volumes:
      - ./docker-elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/mongo/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
      - ./data/elastic-db:/data/db
​
  connector:
    restart: always
    image: matchminer-demo-mongo-connector:1.0.0
    build: docker-mongo-connector
    links:
      - elastic:elasticsearch
      - mongo:mongo
​
  kibana:
    restart: always
    image: matchminer-demo-kibana-sense:1.0.0
    build: docker-kibana-sense
    links:
      - elastic:elasticsearch
    ports:
      - 5601:5601
​
  ui:
    restart: always
    image: matchminer-demo-ui:1.0.0
    links:
        - elastic:elasticsearch
        - api:mmapi
    ports:
      - 8001:8001
```
